#! bin/bash

Script Name                Ops Challenge 03
Author                     Kimberley Cabrera-Boggs
Date of last revision      September 2, 2020
Description of purpose     File Permissions

# 
