#! bin/bash

# Script Name             Ops Challenge 12
# Author                  Kimberley Cabrera-Boggs
# Date of last revision   September 15, 2020
# Description of purpose  Psutil

import psutil

cpyInfo = str(psutil.cpu_times())
result = cpuInfo.split(",")
print(result)

# Main

# Output the time spent by normal processes in user mode
print(result[0],"second")

# Output the time spent by processes executing in kernel mode
print(result[2],"second")

# Output the time when system was idle
print(result[3],"second")

# Output the time spent by priority processes executing in user mode
print(result[1],"second")

# Output the time spent waiting for I/O to complete
print(result[4],"second")

# Output the time spent for servicing hardware interrupts
print(result[5],"second")

# Output the time spent for servicing software interrupts
print(result[6],"second")

# Output the time spent by other OS running in a virtualized environment
print(result[7],"second")

# Output the time spent running virtual CPU for guest OS under the control of the Linux kernel
print(result[8],"second")

# End
