#! bin/bash

# Script Name             Ops Challenge 12
# Author                  Kimberley Cabrera-Boggs
# Date of last revision   September 15, 2020
# Description of purpose  Psutil

import psutil

cpyInfo = str(psutil.cpu_times())
result = cpuInfo.split(",")
print(result)

# Main

print("Time spent by normal processes executing in user mode")
print("result[0])

print("Time spent by processes executing in kernel mode")
print(result[2])

print("Time when system was idle")
print("result[3]")

print("Time spent by priority processes executing in user mode")
print("result[1]")

print("Time spent waiting for I/O to complete")
print("result[4]")

print("Time spent for servicing hardware interrupts")
print("result[6]")

print("Time spent for servicing software interrupts")
print("result[7]")

print("Time spent by other operating systems running in a virtualized environment
")
print("result[10]")

print("Time spent running a virtual CPU for guest operating systems under the control of the Linux kernel")
print("result[9]")

# End
